<footer class="footer">
    <div class="footer-container container d-flex align-items-start justify-content-between">
        <div class="logo d-none d-md-flex align-items-center">
            <img src="./assets/img/logo.png" alt="logo image" class="logo__img" draggable="false">
            <div class="logo__text d-flex flex-column">
                <span class="logo__text_green">Еда</span> Рядом
            </div>
        </div>
        <div class="footer__element contacts">
            <h3 class="element-heading">Для связи</h3>
            <ul class="element-content d-flex flex-column">
                <li class="title-medium">
                    WhatsApp: +7‒952‒000‒72‒24
                </li>
                <li class="title-medium">
                    E-mail: eda22@bk.ru
                </li>
                <li class="title-medium">
                    Телефон: 25‒19‒98
                </li>
            </ul>
        </div>
        <div class="footer__element navigation d-none d-md-flex flex-column">
            <h3 class="element-heading">Навигация</h3>
            <ul class="element-content d-flex flex-column" id="footerNav">
                <li class="title-medium">
                    <a class="element-content-row__list-link" href="#">Главная</a>
                </li>
                <li class="title-medium">
                    <a class="element-content-row__list-link" href="./catalog">Каталог</a>
                </li>
                <li class="title-medium">
                    <a class="element-content-row__list-link" href="./contacts">Контакты</a>
                </li>
                <li class="title-medium">
                    <a class="element-content-row__list-link" href="./checkout/sign_in">Войти</a>
                </li>
            </ul>
        </div>
    </div>
</footer>