<header class="header">
    <div class="header-panel container d-flex justify-content-center align-items-center">
        <div class="logo d-flex align-items-center">
            <img src="../assets/img/logo.png" alt="logo image" class="logo__img" draggable="false">
            <div class="logo__text d-flex flex-column">
                <span class="logo__text_green">Еда</span> Рядом
            </div>
        </div>
    </div>
</header>